name: Deploy to Firebase

on:
  pull_request:
    branches: [main]
  workflows_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14
          cache: "npm"
      - run: npm ci

      - name: Setup Node.js
      
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
      code_quality:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14
          cache: "npm"
      - run: npm ci
      - run: npm run lint
      - run: npm run prettier

      - name: Deploy to Firebase
        run: |
          npm install -g firebase-tools
          firebase deploy --token "$FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
